package processdefinition;

import org.axonframework.commandhandling.gateway.CommandGateway;

import passiveprocessengine.instance.QACheckDocument;
import passiveprocessengine.instance.WorkflowTask;
import passiveprocessengine.instance.ResourceLink;
import java.util.Optional;
import passiveprocessengine.instance.RuleEngineBasedConstraint;
import java.time.Instant;
import passiveprocessengine.instance.CorrelationTuple;
import passiveprocessengine.instance.ConstraintTrigger;
import passiveprocessengine.instance.WorkflowInstance;
import passiveprocessengine.instance.ArtifactWrapper;

import impactassessment.api.Commands.AddEvaluationResultToConstraintCmd;
import impactassessment.api.Commands.AddOutputCmd;
import impactassessment.api.Commands.AddConstraintsCmd;
import java.util.concurrent.TimeUnit;
import java.util.List;
import java.util.ArrayList;

import artifactapi.IArtifactRegistry;
import artifactapi.jira.IJiraArtifact;
import artifactapi.jama.IJamaArtifact;
import artifactapi.jira.subtypes.IJiraIssueLink;
import artifactapi.IArtifactRegistry;

import impactassessment.kiesession.KieSessionUtils;
import java.util.Map;
import java.util.HashMap;


import passiveprocessengine.instance.ResourceLink;
import passiveprocessengine.instance.WorkflowTask;
import artifactapi.jama.subtypes.IJamaRelease
import impactassessment.artifactconnector.jama.JamaArtifact
import artifactapi.ArtifactIdentifier
import impactassessment.artifactconnector.jira.JiraArtifact
import artifactapi.IArtifact;
import c4s.impactassessment.workflowmodel.TaskLifecycle.*;

import passiveprocessengine.definition.*;
import passiveprocessengine.instance.*;
import passiveprocessengine.definition.ArtifactTypes;
import passiveprocessengine.definition.ArtifactType;

global CommandGateway commandGateway;
global IArtifactRegistry artifactRegistry;

//constraints for state open
rule "InsertQAConstraintsDemo"
	when
		$wft : WorkflowTask(    getType().getId().equals("DemoTask") &&
		                        getAnyOneOutputByRole(ArtifactTypes.ARTIFACT_TYPE_QA_CHECK_DOCUMENT) == null)
	then
        Map<String, String> constraints = new HashMap<>();
        constraints.put("CheckJiraName", "Does Jira issue have the right name ?");
        commandGateway.send(new AddConstraintsCmd($wft.getWorkflow().getId(), $wft.getId(), constraints));
end


rule "CheckJiraName" 
	no-loop
	when
		$ct : ConstraintTrigger()
		$qac : RuleEngineBasedConstraint( isAffectedBy($ct) && getConstraintType().equals( "CheckJiraName" ))
		$wft : WorkflowTask( getType().getId().equals("DemoTask") , $jira : getAnyOneInputByRole("root") )
		eval ($jira != null)
	then
		System.out.println("Checking: "+$qac.getId() +" in workflow " +$wft.getWorkflow().getId());
		IJiraArtifact ja = (IJiraArtifact) ((ArtifactWrapper)$jira).getWrappedArtifact();
		boolean hasName = ja.getIssueType().getName().equalsIgnoreCase("Design Definition");
		Map<ResourceLink, Boolean> result = Map.of(ja.convertToResourceLink(), hasName);
		commandGateway.send(new AddEvaluationResultToConstraintCmd($qac.getWorkflow().getId(), $qac.getId(), result, $ct.getRequestCorrelation(), Instant.now()));
end




rule "CompleteDemoTask"
	when
		$wft : WorkflowTask (   getType().getId().equals("DemoTask") &&
								!(getLifecycleState().equals(TaskLifecycle.State.COMPLETED)) &&
								 getAnyOneOutputByRole("outDoc") == null 
								 , $jira : getAnyOneInputByRole("root") 								
							 ) @watch( lifecycleState )
		eval ($jira != null )					 //"UAV-1196"
	then
		IJiraArtifact artOut = (IJiraArtifact) artifactRegistry.get(new ArtifactIdentifier("PVCSG-3409", "IJiraArtifact"), $wft.getWorkflow().getId()).get();
		Artifact art = new ArtifactWrapper(artOut.getKey(), "IJiraArtifact", $wft.getWorkflow(), artOut);
		commandGateway.send(new AddOutputCmd($wft.getWorkflow().getId(), $wft.getId(), art, "outDoc", new ArtifactType("IJiraArtifact") ));
end


rule "RemoveConstraintTrigger"
	salience -1000
	when
		$ct : ConstraintTrigger()
	then
		delete($ct);
end