@startuml

skin rose

title Process Guidance Framework - Dependency Diagram (managed via Maven)

package "DesignSpace" {
component [DesignSpace.Core] as core
component [DesignSpace.Rule] as rule
}

note top of core
defines <<InstanceType>> and <Instance>
end note
note bottom of rule
defines <<ConsistencyRuleType>> and <ConsistencyRule> 
and all rule expression, evaluation, and repair tree classes
end note

package "PPE" {
component [PPE.Core] as ppe 
component [PPE.UI] as ui
component [PPE.REST + BlocklyEditor] as rest
component [Transformation.Stages] as stages
component [Transformation.Blockly] as blockly
component [OCL DSL] as oclx
}

note top of ppe
defines all process definition and instance related types
end note

package "Tool Connectors" {
component [ToolConnector.Core] as tool
component [DSWrapper] as wrapper
component [ToolConnector.Azure] as azure 
component [JiraAuthenticaor] as jiraAuth
}

note bottom of azure
defines <WorkItemType>
end note

note bottom of jiraAuth
ignore, only needed for experiments
end note

rule -up-> core

wrapper -up-> tool: implements
wrapper -up-> core
wrapper -up-> rule
azure -up-> tool
jiraAuth -up-> tool

ppe -up-> tool
blockly -up-> ppe

stages -up-> ppe
stages -up-> azure



ui -up-> rest
ui -up-> oclx
oclx -up-> tool
rest -up-> azure
rest -up-> stages
rest -up-> blockly
rest -up-> rule

@enduml