package rules;
dialect  "mvel"

import impactassessment.rulebase.Count;
import impactassessment.utils.SpringContext;
import org.axonframework.commandhandling.gateway.CommandGateway
import impactassessment.api.EnableCmd;
import impactassessment.workflowmodel.*;
import impactassessment.workflowmodel.definition.*;
import impactassessment.workflowmodel.definition.QACheckDocument.QAConstraint.EvaluationState;

global CommandGateway commandGateway;

rule "increment"
    when
        Count( )
    then
        System.out.println("Hello there from the KB!!");
        commandGateway.send(new EnableCmd("1", 0));
end

rule "CheckSWRequirementReleased"
	no-loop
	when
		$qaConst : RuleEngineBasedConstraint( getConstraintType().equals( "CheckSWRequirementReleased" ) )
		$ct : ConstraintTrigger ( )
	then
	    System.out.println("Hello there from the KB!!");
		modify($qaConst) {
            setEvaluationStatusMessage("") ,
            setEvaluationStatus(EvaluationState.SUCCESS) ,
            setLastChangeDueTo($ct.getRequestCorrelation())
        };
end
