package rules;

import org.slf4j.Logger
import org.axonframework.commandhandling.gateway.CommandGateway

import impactassessment.model.*;
import impactassessment.model.definition.*;
import impactassessment.model.definition.QACheckDocument.QAConstraint.EvaluationState;
import impactassessment.mock.artifact.Artifact;

global CommandGateway commandGateway;
global Logger log;

/*
rule "SimpleTest2"
    when
        Artifact(  )
    then
        log.debug("input.drl: rule SimpleTest2");
end
*/

rule "EvaluationRule"
	no-loop
	when
	    $ct : ConstraintTrigger ( )
		$qaConst : RuleEngineBasedConstraint( getWorkflow().getId().equals($ct.getWorkflow().getId())
		                                        && getConstraintType().equals( "EvaluationRule" ) )
	then
		modify($qaConst) {
            setEvaluationStatusMessage("We evaluated some stuff") ,
            setEvaluationStatus(EvaluationState.SUCCESS) ,
            setLastChangeDueTo($ct.getRequestCorrelation())
        };
end
