//created on: 25.05.2021
package defaultrules

import impactassessment.api.Events.UpdatedArtifactsEvt
import impactassessment.api.Events.IdentifiableEvt
import passiveprocessengine.instance.ConstraintTrigger
import passiveprocessengine.instance.WorkflowChangeEvent


rule "RemoveConstraintTrigger"
	salience -1000
	when
		$ct : ConstraintTrigger()
	then
		delete($ct);
end

rule "RemoveArtifactUpdateEvent"
	salience 2000
	when
		$aue : UpdatedArtifactsEvt()
	then
		delete($aue);
end

rule "RemoveAnyIdentifiableEvt"
	salience 1999
	when 
		$ie : IdentifiableEvt()
	then
		delete($ie);
end

rule "RemoveAnyWorkflowChangeEvents"
	salience -1000
	when
		$wce : WorkflowChangeEvent()
	then
		delete($wce);
end
